#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export JAVA_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home"
export GIT_BASE="$HOME/git"
export MYSQL_HOME="$(brew --prefix mysql@5.7)"
export GOPATH="$HOME/go"

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)
eval `$HOME/bin/path_helper.pl ./.paths ./.paths.d ./.man_paths`

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
# export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
# if (( $#commands[(i)lesspipe(|.sh)] )); then
#   export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
# fi

export LESS="-x4 -m -R"
export LESSOPEN="| highlight -q --out-format=truecolor --base16 --style=tomorrow-night %s"

# for use with java 8
export JAVA_OPTS="-Xms256m -Xmx2g"

# export MAVEN_OPTS="$MAVEN_OPTS $JAVA_OPTS -javaagent:/Users/ddclarryg/git/build/lib/spring-instrument-3.1.0.RELEASE.jar -Dorg.mortbay.xml.XmlParser.NotValidating=true"
export MAVEN_OPTS="$MAVEN_OPTS $JAVA_OPTS -Dorg.aspectj.weaver.showWeaveInfo=false -Dorg.mortbay.xml.XmlParser.NotValidating=true -javaagent:/Users/ddclarryg/git/build/lib/aspectjweaver-1.8.4.jar -javaagent:/Users/ddclarryg/git/build/lib/spring-instrument-3.1.0.RELEASE.jar"


export SUGAR="4341464542414245"


