#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR=vim

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


POWERLEVEL9K_MODE='nerdfont-complete'

export DEFAULT_USER=$USER
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs virtualenv time)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs virtualenv custom_lpg time)
POWERLEVEL9K_CUSTOM_LPG="alks-whoami"
POWERLEVEL9K_CUSTOM_LPG_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_LPG_FOREGROUND="yellow"

for i in $HOME/.zsh.d/*.sh; do source $i; done
unset -v i

